### ISSUE TITLE
Rapidshare checking not working

### ISSUE THREAD

**Issue by NewEraCracker** [NewEraCracker/IPB3LinkBot#1]
Needs to be fixed.

**Comment by Guims** [comment]
Good evening,

Thank for you script !!!

I know that your application goes back to 2010 but I have nevertheless to try to install it on IPB 3.3.4.
all functions is work but impossible to launch the spot in the run task, I obtain a white page and when I return above, it indicates to me that it is locked.

could you help me?

cordially
